### ISSUE TITLE
Is it possible to run xgo on gitlab.com CI?

### ISSUE THREAD

**Issue by ykyuen** [tehsphinx/gitlab-ci-xgo#1]
I am using gitlab.com CI with the shared runner and so i dun have the config.toml. Any idea to run xgo using the dind service?

Actually i have raised the question on gitlab.com support tracker but so far got no reply yet.
[Problem when compilng go binary using xgo with dind](https://gitlab.com/gitlab-com/support-forum/issues/2620)

Any idea would be appreciated. thanks~~

**Comment by tehsphinx** [comment]
With this package it is not possible. Problem is, that xgo is creating docker images and runs code in them. To do this it needs access to docker and you give it access in the `config.toml`.

You could try installing docker in a docker container, but I can't say if that is supported on dind service.

**Comment by ykyuen** [comment]
Thx for your reply. finally i came out with a workaround which had to forked the [xgo](https://github.com/ykyuen/xgo) repository with the following changes.

1. Make the mount points writable.
2. Copy the built binary from the `/build` folder to the project root directory and the end of the xgo execution.

I wonder if making those mount points writable would lead to any problem, but currently that's the only way i could use xgo in gitlab pipeline.

Thanks again. =D
